-- Books & Runs — safety layer: block users, report users, and a content
-- filter on public text (display names, bios, club/tournament names).
-- Run this once in the Supabase SQL editor, after 0001–0059.
--
--   1. user_blocks + block_user()/unblock_user()/my_blocks()/is_blocked_pair()
--      Blocking removes any friendship, drops the blocked account's unseen
--      requests, and from then on:
--        • the two accounts can't become friends (trigger on friendships —
--          covers friend requests AND friend-code links),
--        • friend-code lookup of the blocker returns "no such code",
--        • neither can invite the other to a game (the `mp` function checks
--          is_blocked_pair), and the blocker no longer sees the blocked
--          account's emotes (RLS on mp_emotes, migration 0061),
--        • the leaderboard RPCs (0063) hide them from each other.
--      Nothing tells the blocked account it happened.
--   2. user_reports + report_user() — one report per (reporter, target,
--      kind), rate-limited, with a snapshot of the reported name/bio so a
--      later edit can't erase the evidence. No read policy at all: rows are
--      read only from the dashboard / service role. report_profile_photo()
--      (0025/0049) now files into the same table, so there is one queue.
--   3. content_blocklist + content_flagged() + triggers — server-side
--      enforcement of the same rules as src/safety/contentFilter.ts (the
--      client pre-check). The list below is GENERATED by
--      scripts/gen-blocklist-sql.mjs from src/safety/blocklist.ts; a unit
--      test fails if this file drifts from it. Only NEW values are checked
--      (a name/bio that is unchanged is never re-validated), and the
--      trigger fails open: an unexpected error in the check lets the write
--      through rather than locking anyone out of saving their profile.
--
-- Reviewing reports (SQL editor):
--   select r.created_at, r.kind, r.reason, r.note, r.context,
--          le.display_name as reported_name, r.snapshot
--   from public.user_reports r
--   left join public.leaderboard_entries le on le.user_id = r.reported_user_id
--   where r.status = 'open' order by r.created_at desc;

-- ─────────────────────────────────────────────────────────────────────────
-- 1. blocks
-- ─────────────────────────────────────────────────────────────────────────

create table if not exists public.user_blocks (
  blocker_id uuid not null references auth.users (id) on delete cascade,
  blocked_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create index if not exists user_blocks_blocked on public.user_blocks (blocked_id);

alter table public.user_blocks enable row level security;

-- You can read your own block list. Nobody can read who blocked THEM, and
-- all writes go through the RPCs below.
drop policy if exists "user_blocks: blocker read" on public.user_blocks;
create policy "user_blocks: blocker read" on public.user_blocks
  for select using (auth.uid() = blocker_id);

-- Either direction. Internal helper (security definer so RLS-restricted
-- callers can still ask it); not granted to clients.
create or replace function public.is_blocked_pair(a uuid, b uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.user_blocks
    where (blocker_id = a and blocked_id = b) or (blocker_id = b and blocked_id = a)
  );
$$;

revoke execute on function public.is_blocked_pair(uuid, uuid) from anon, public, authenticated;

create or replace function public.block_user(p_user uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare me uuid := auth.uid();
begin
  if me is null then raise exception 'not authenticated'; end if;
  if p_user is null or p_user = me then raise exception 'invalid target'; end if;
  if not exists (select 1 from auth.users where id = p_user) then raise exception 'no such user'; end if;

  perform public.mp_bump_rate_limit('block_user', 60);

  insert into public.user_blocks (blocker_id, blocked_id) values (me, p_user)
    on conflict do nothing;

  -- Unfriend / drop any pending request in either direction.
  delete from public.friendships
    where (requester_id = me and addressee_id = p_user)
       or (requester_id = p_user and addressee_id = me);
  -- Clear their unseen friend requests / invites from my inbox.
  delete from public.mp_events
    where user_id = me and actor_id = p_user and seen_at is null
      and kind in ('friend_request', 'friend_accepted', 'game_request', 'nudge');
end;
$$;

create or replace function public.unblock_user(p_user uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare me uuid := auth.uid();
begin
  if me is null then raise exception 'not authenticated'; end if;
  delete from public.user_blocks where blocker_id = me and blocked_id = p_user;
end;
$$;

create or replace function public.my_blocks()
returns table (user_id uuid, display_name text, blocked_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare me uuid := auth.uid();
begin
  if me is null then raise exception 'not authenticated'; end if;
  return query
    select b.blocked_id, le.display_name, b.created_at
    from public.user_blocks b
    left join public.leaderboard_entries le on le.user_id = b.blocked_id
    where b.blocker_id = me
    order by b.created_at desc;
end;
$$;

revoke execute on function public.block_user(uuid), public.unblock_user(uuid), public.my_blocks()
  from anon, public;
grant execute on function public.block_user(uuid), public.unblock_user(uuid), public.my_blocks()
  to authenticated;

-- Blocked pairs can't (re)connect. Covers mp_send_friend_request and
-- mp_add_friend_by_code without redefining either. The message is neutral
-- and does not reveal who blocked whom.
create or replace function public.friendships_block_guard()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_blocked_pair(new.requester_id, new.addressee_id) then
    raise exception 'You can''t connect with this player' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

drop trigger if exists friendships_block_guard on public.friendships;
create trigger friendships_block_guard
  before insert or update on public.friendships
  for each row execute function public.friendships_block_guard();

-- Friend-code lookup: a blocked pair can't find each other. (Body is 0013's
-- plus the block filter.)
create or replace function public.mp_lookup_friend_code(code text)
returns table (user_id uuid, display_name text)
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
begin
  if me is null then raise exception 'not authenticated'; end if;
  perform public.mp_bump_rate_limit('friend_code_lookup', 60);
  return query
    select p.id, le.display_name
    from public.profiles p
    left join public.leaderboard_entries le on le.user_id = p.id
    where upper(p.friend_code) = upper(trim(code))
      and not public.is_blocked_pair(me, p.id)
    limit 1;
end;
$$;

revoke execute on function public.mp_lookup_friend_code(text) from anon, public;
grant execute on function public.mp_lookup_friend_code(text) to authenticated;

-- ─────────────────────────────────────────────────────────────────────────
-- 2. reports
-- ─────────────────────────────────────────────────────────────────────────

create table if not exists public.user_reports (
  id uuid primary key default gen_random_uuid(),
  -- Kept (set null) if the reporter later deletes their account, so a report
  -- doesn't vanish with them; removed with the reported account.
  reporter_id uuid references auth.users (id) on delete set null,
  reported_user_id uuid not null references auth.users (id) on delete cascade,
  kind text not null check (kind in ('name', 'bio', 'photo', 'behavior', 'other')),
  reason text not null check (reason in
    ('offensive', 'harassment', 'impersonation', 'cheating', 'spam', 'inappropriate_photo', 'other')),
  note text check (note is null or char_length(note) <= 280),
  -- Where it was filed from: profile | friends | mp_game | club | tournament | leaderboard
  context text check (context is null or char_length(context) <= 32),
  game_id uuid,
  -- The reported account's public text when it was reported.
  snapshot jsonb not null default '{}'::jsonb,
  status text not null default 'open' check (status in ('open', 'reviewed', 'actioned', 'dismissed')),
  created_at timestamptz not null default now()
);

create unique index if not exists user_reports_once
  on public.user_reports (reporter_id, reported_user_id, kind) where reporter_id is not null;
create index if not exists user_reports_open on public.user_reports (status, created_at desc);

alter table public.user_reports enable row level security;
-- Deliberately NO policies: not readable or writable from any client.

-- Bring over any existing photo reports (0025) so there's a single queue.
insert into public.user_reports (reporter_id, reported_user_id, kind, reason, note, created_at)
select reporter_id, reported_user_id, 'photo', 'inappropriate_photo', reason, created_at
from public.profile_photo_reports
on conflict do nothing;

create or replace function public.report_user(
  p_reported_user_id uuid,
  p_kind text,
  p_reason text,
  p_note text default null,
  p_game_id uuid default null,
  p_context text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  snap jsonb;
begin
  if me is null then raise exception 'not authenticated'; end if;
  if p_reported_user_id is null or p_reported_user_id = me then raise exception 'cannot report yourself'; end if;
  if p_kind not in ('name', 'bio', 'photo', 'behavior', 'other') then raise exception 'invalid report'; end if;
  if p_reason not in ('offensive', 'harassment', 'impersonation', 'cheating', 'spam', 'inappropriate_photo', 'other') then
    raise exception 'invalid report';
  end if;
  if not exists (select 1 from auth.users where id = p_reported_user_id) then raise exception 'no such user'; end if;

  perform public.mp_bump_rate_limit('report_user', 20);

  select jsonb_build_object(
    'display_name', le.display_name,
    'bio', le.bio,
    'avatar_kind', le.avatar_kind,
    'avatar_photo_path', le.avatar_photo_path
  ) into snap
  from public.leaderboard_entries le where le.user_id = p_reported_user_id;

  insert into public.user_reports (reporter_id, reported_user_id, kind, reason, note, context, game_id, snapshot)
    values (
      me, p_reported_user_id, p_kind, p_reason,
      nullif(left(btrim(coalesce(p_note, '')), 280), ''),
      left(p_context, 32), p_game_id, coalesce(snap, '{}'::jsonb)
    )
    on conflict (reporter_id, reported_user_id, kind) where reporter_id is not null do nothing;
end;
$$;

revoke execute on function public.report_user(uuid, text, text, text, uuid, text) from anon, public;
grant execute on function public.report_user(uuid, text, text, text, uuid, text) to authenticated;

-- Older clients still call report_profile_photo(); route it into the same
-- queue instead of the legacy table.
create or replace function public.report_profile_photo(p_reported_user_id uuid, p_reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.report_user(p_reported_user_id, 'photo', 'inappropriate_photo', p_reason, null, 'profile');
end;
$$;

revoke execute on function public.report_profile_photo(uuid, text) from anon, public;
grant execute on function public.report_profile_photo(uuid, text) to authenticated;

-- ─────────────────────────────────────────────────────────────────────────
-- 3. content filter
-- ─────────────────────────────────────────────────────────────────────────

create table if not exists public.content_blocklist (
  term text not null,        -- normalised, runs of 3+ letters cut to 2
  term_loose text not null,  -- normalised, every run cut to 1
  mode text not null check (mode in ('sub', 'stem', 'word', 'res_exact', 'res_contains', 'res_prefix')),
  primary key (term, mode)
);

alter table public.content_blocklist enable row level security;
-- No policies: only the security-definer functions below read it.

-- BEGIN GENERATED (scripts/gen-blocklist-sql.mjs)
insert into public.content_blocklist (term, term_loose, mode) values
  ('nigger', 'niger', 'sub'),
  ('nigga', 'niga', 'sub'),
  ('faggot', 'fagot', 'sub'),
  ('motherfuck', 'motherfuck', 'sub'),
  ('cocksuck', 'cocksuck', 'sub'),
  ('heilhitler', 'heilhitler', 'sub'),
  ('whitepower', 'whitepower', 'sub'),
  ('gasthejews', 'gasthejews', 'sub'),
  ('fuck', 'fuck', 'stem'),
  ('shit', 'shit', 'stem'),
  ('cunt', 'cunt', 'stem'),
  ('bitch', 'bitch', 'stem'),
  ('whore', 'whore', 'stem'),
  ('slut', 'slut', 'stem'),
  ('pussy', 'pusy', 'stem'),
  ('asshole', 'ashole', 'stem'),
  ('bastard', 'bastard', 'stem'),
  ('retard', 'retard', 'stem'),
  ('jizz', 'jiz', 'stem'),
  ('porn', 'porn', 'stem'),
  ('paedo', 'paedo', 'stem'),
  ('pedophil', 'pedophil', 'stem'),
  ('rapist', 'rapist', 'stem'),
  ('dick', 'dick', 'word'),
  ('cock', 'cock', 'word'),
  ('twat', 'twat', 'word'),
  ('cum', 'cum', 'word'),
  ('kike', 'kike', 'word'),
  ('chink', 'chink', 'word'),
  ('spic', 'spic', 'word'),
  ('tranny', 'trany', 'word'),
  ('pedo', 'pedo', 'word'),
  ('rape', 'rape', 'word'),
  ('kk', 'k', 'word'),
  ('kys', 'kys', 'word'),
  ('penis', 'penis', 'word'),
  ('vagina', 'vagina', 'word'),
  ('tits', 'tits', 'word'),
  ('wank', 'wank', 'word'),
  ('wanker', 'wanker', 'word'),
  ('wankers', 'wankers', 'word'),
  ('mierda', 'mierda', 'stem'),
  ('cabron', 'cabron', 'stem'),
  ('pendejo', 'pendejo', 'stem'),
  ('joder', 'joder', 'stem'),
  ('culero', 'culero', 'stem'),
  ('hijueputa', 'hijueputa', 'stem'),
  ('hijodeputa', 'hijodeputa', 'stem'),
  ('verga', 'verga', 'word'),
  ('cono', 'cono', 'word'),
  ('zorra', 'zora', 'word'),
  ('puta', 'puta', 'word'),
  ('putas', 'putas', 'word'),
  ('puto', 'puto', 'word'),
  ('putos', 'putos', 'word'),
  ('putita', 'putita', 'word'),
  ('marica', 'marica', 'word'),
  ('maricon', 'maricon', 'word'),
  ('maricones', 'maricones', 'word'),
  ('chinga', 'chinga', 'word'),
  ('chingar', 'chingar', 'word'),
  ('chingada', 'chingada', 'word'),
  ('chingado', 'chingado', 'word'),
  ('chingon', 'chingon', 'word'),
  ('putain', 'putain', 'stem'),
  ('connard', 'conard', 'stem'),
  ('connasse', 'conase', 'stem'),
  ('encule', 'encule', 'stem'),
  ('batard', 'batard', 'stem'),
  ('enfoire', 'enfoire', 'stem'),
  ('couille', 'couile', 'stem'),
  ('merde', 'merde', 'word'),
  ('pute', 'pute', 'word'),
  ('ntm', 'ntm', 'word'),
  ('fdp', 'fdp', 'word'),
  ('salope', 'salope', 'word'),
  ('salopes', 'salopes', 'word'),
  ('nique', 'nique', 'word'),
  ('niquer', 'niquer', 'word'),
  ('scheiss', 'scheis', 'stem'),
  ('arschloch', 'arschloch', 'stem'),
  ('fotze', 'fotze', 'stem'),
  ('wichser', 'wichser', 'stem'),
  ('schlampe', 'schlampe', 'stem'),
  ('missgeburt', 'misgeburt', 'stem'),
  ('schwuchtel', 'schwuchtel', 'stem'),
  ('kanake', 'kanake', 'stem'),
  ('hurensohn', 'hurensohn', 'sub'),
  ('neger', 'neger', 'word'),
  ('spast', 'spast', 'word'),
  ('hure', 'hure', 'word'),
  ('fick', 'fick', 'word'),
  ('ficken', 'ficken', 'word'),
  ('ficker', 'ficker', 'word'),
  ('nutte', 'nute', 'word'),
  ('nutten', 'nuten', 'word'),
  ('cazzo', 'cazo', 'stem'),
  ('stronz', 'stronz', 'stem'),
  ('puttana', 'putana', 'stem'),
  ('minchia', 'minchia', 'stem'),
  ('coglione', 'coglione', 'stem'),
  ('frocio', 'frocio', 'stem'),
  ('fanculo', 'fanculo', 'stem'),
  ('merda', 'merda', 'stem'),
  ('vaffanculo', 'vafanculo', 'sub'),
  ('porcodio', 'porcodio', 'sub'),
  ('porcamadonna', 'porcamadona', 'sub'),
  ('troia', 'troia', 'word'),
  ('caralho', 'caralho', 'stem'),
  ('buceta', 'buceta', 'stem'),
  ('viado', 'viado', 'stem'),
  ('arrombad', 'arombad', 'stem'),
  ('vagabund', 'vagabund', 'stem'),
  ('punheta', 'punheta', 'stem'),
  ('otario', 'otario', 'stem'),
  ('cuzao', 'cuzao', 'stem'),
  ('filhodaputa', 'filhodaputa', 'sub'),
  ('porra', 'pora', 'word'),
  ('foda', 'foda', 'word'),
  ('cacete', 'cacete', 'word'),
  ('хуй', 'хуй', 'stem'),
  ('хуе', 'хуе', 'stem'),
  ('пизд', 'пизд', 'stem'),
  ('ебан', 'ебан', 'stem'),
  ('ебат', 'ебат', 'stem'),
  ('ебал', 'ебал', 'stem'),
  ('бляд', 'бляд', 'stem'),
  ('блят', 'блят', 'stem'),
  ('мудак', 'мудак', 'stem'),
  ('мудил', 'мудил', 'stem'),
  ('гандон', 'гандон', 'stem'),
  ('пидор', 'пидор', 'stem'),
  ('пидар', 'пидар', 'stem'),
  ('залуп', 'залуп', 'stem'),
  ('шлюх', 'шлюх', 'stem'),
  ('blyat', 'blyat', 'stem'),
  ('blyad', 'blyad', 'stem'),
  ('pidor', 'pidor', 'stem'),
  ('pidar', 'pidar', 'stem'),
  ('pizd', 'pizd', 'stem'),
  ('mudak', 'mudak', 'stem'),
  ('ebat', 'ebat', 'stem'),
  ('нахуй', 'нахуй', 'sub'),
  ('долбоеб', 'долбоеб', 'sub'),
  ('nahuy', 'nahuy', 'sub'),
  ('чмо', 'чмо', 'word'),
  ('huy', 'huy', 'word'),
  ('suka', 'suka', 'word'),
  ('сука', 'сука', 'word'),
  ('суки', 'суки', 'word'),
  ('суку', 'суку', 'word'),
  ('死ね', '死ね', 'sub'),
  ('殺す', '殺す', 'sub'),
  ('ちんこ', 'ちんこ', 'sub'),
  ('まんこ', 'まんこ', 'sub'),
  ('ちんぽ', 'ちんぽ', 'sub'),
  ('キチガイ', 'キチガイ', 'sub'),
  ('ガイジ', 'ガイジ', 'sub'),
  ('ファック', 'ファック', 'sub'),
  ('レイプ', 'レイプ', 'sub'),
  ('씨발', '씨발', 'sub'),
  ('시발', '시발', 'sub'),
  ('개새끼', '개새끼', 'sub'),
  ('병신', '병신', 'sub'),
  ('지랄', '지랄', 'sub'),
  ('좆', '좆', 'sub'),
  ('존나', '존나', 'sub'),
  ('미친놈', '미친놈', 'sub'),
  ('창녀', '창녀', 'sub'),
  ('느금마', '느금마', 'sub'),
  ('ᄉᄇ', 'ᄉᄇ', 'sub'),
  ('ᄇᄉ', 'ᄇᄉ', 'sub'),
  ('ᄌᄅ', 'ᄌᄅ', 'sub'),
  ('傻逼', '傻逼', 'sub'),
  ('傻屄', '傻屄', 'sub'),
  ('煞笔', '煞笔', 'sub'),
  ('操你妈', '操你妈', 'sub'),
  ('草泥马', '草泥马', 'sub'),
  ('他妈的', '他妈的', 'sub'),
  ('王八蛋', '王八蛋', 'sub'),
  ('狗屎', '狗屎', 'sub'),
  ('去死', '去死', 'sub'),
  ('婊子', '婊子', 'sub'),
  ('贱人', '贱人', 'sub'),
  ('妓女', '妓女', 'sub'),
  ('强奸', '强奸', 'sub'),
  ('鸡巴', '鸡巴', 'sub'),
  ('肏', '肏', 'sub'),
  ('干你娘', '干你娘', 'sub'),
  ('日你妈', '日你妈', 'sub'),
  ('脑残', '脑残', 'sub'),
  ('死全家', '死全家', 'sub'),
  ('支那', '支那', 'sub'),
  ('nmsl', 'nmsl', 'word'),
  ('admin', 'admin', 'res_exact'),
  ('administrator', 'administrator', 'res_exact'),
  ('moderator', 'moderator', 'res_exact'),
  ('mod', 'mod', 'res_exact'),
  ('support', 'support', 'res_exact'),
  ('staff', 'staff', 'res_exact'),
  ('official', 'official', 'res_exact'),
  ('system', 'system', 'res_exact'),
  ('developer', 'developer', 'res_exact'),
  ('dev', 'dev', 'res_exact'),
  ('owner', 'owner', 'res_exact'),
  ('creator', 'creator', 'res_exact'),
  ('gamemaster', 'gamemaster', 'res_exact'),
  ('gm', 'gm', 'res_exact'),
  ('deletedplayer', 'deletedplayer', 'res_exact'),
  ('anonymous', 'anonymous', 'res_exact'),
  ('booksandruns', 'booksandruns', 'res_exact'),
  ('booksruns', 'booksruns', 'res_exact'),
  ('booksandruns', 'booksandruns', 'res_contains'),
  ('booksruns', 'booksruns', 'res_contains'),
  ('booksnruns', 'booksnruns', 'res_contains'),
  ('bookandruns', 'bookandruns', 'res_contains'),
  ('admin', 'admin', 'res_prefix'),
  ('moderator', 'moderator', 'res_prefix')
on conflict (term, mode) do nothing;
-- END GENERATED

-- Mirrors foldText() in src/safety/contentFilter.ts: NFKC, lower-case,
-- ß/æ/œ expansion, then a 1:1 accent-fold and leet-fold translate.
create or replace function public.content_fold(t text)
returns text
language sql
immutable
as $$
  select translate(
    replace(replace(replace(lower(normalize(coalesce(t, ''), NFKC)), 'ß', 'ss'), 'æ', 'ae'), 'œ', 'oe'),
    'àáâãäåāăąçćčďđèéêëēėęěìíîïīįłñńňòóôõöøōőŕřśšşťùúûüūůűųýÿźżžё013457@$',
    'aaaaaaaaacccddeeeeeeeeiiiiiilnnnoooooooorrssstuuuuuuuuyyzzzеoieastas'
  );
$$;

-- "f u c k" / "f.u.c.k": runs of 3+ single-letter words become one word.
create or replace function public.content_words(folded text)
returns text[]
language plpgsql
immutable
as $$
declare
  out_ text[] := '{}';
  buf text := '';
  n int := 0;
  w text;
begin
  for w in select x from regexp_split_to_table(folded, '[^[:alnum:]]+') x where x <> '' loop
    if w ~ '^[a-z]$' then
      buf := buf || w;
      n := n + 1;
    else
      if n >= 3 then out_ := out_ || buf;
      elsif n > 0 then out_ := out_ || regexp_split_to_array(buf, '');
      end if;
      buf := '';
      n := 0;
      out_ := out_ || w;
    end if;
  end loop;
  if n >= 3 then out_ := out_ || buf;
  elsif n > 0 then out_ := out_ || regexp_split_to_array(buf, '');
  end if;
  return out_;
end;
$$;

-- Returns null when the text is fine, else 'empty' | 'profanity' |
-- 'impersonation' | 'link'. kind: 'name' | 'bio' | 'title'.
create or replace function public.content_flagged(t text, kind text default 'name')
returns text
language plpgsql
stable
as $$
declare
  folded text;
  words text[];
  sq text;
begin
  if t is null or btrim(t) = '' then
    return case when kind = 'bio' then null else 'empty' end;
  end if;

  folded := public.content_fold(btrim(t));
  words := public.content_words(folded);
  sq := regexp_replace(
    array_to_string(array(select x from regexp_split_to_table(folded, '[^[:alnum:]]+') x where x <> ''), ''),
    '([a-z])\1{2,}', '\1\1', 'g');

  if exists (
    select 1 from public.content_blocklist b
    where b.mode = 'sub' and b.term <> '' and position(b.term in sq) > 0
  ) then
    return 'profanity';
  end if;

  -- w3: runs of 3+ letters cut to 2; the fully-collapsed comparison only
  -- applies to words that were actually stretched (fuuuck, not shiitake).
  if exists (
    select 1
    from public.content_blocklist b
    cross join lateral (
      select regexp_replace(x, '([a-z])\1{2,}', '\1\1', 'g') as w3,
             (x ~ '([a-z])\1{2,}') as stretched
      from unnest(words) as x
    ) u
    where b.term <> '' and (
      (b.mode = 'stem' and (
        left(u.w3, length(b.term)) = b.term
        or (u.stretched and left(regexp_replace(u.w3, '([a-z])\1+', '\1', 'g'), length(b.term_loose)) = b.term_loose)))
      or (b.mode = 'word' and (
        u.w3 = b.term
        or (u.stretched and regexp_replace(u.w3, '([a-z])\1+', '\1', 'g') = b.term_loose)))
    )
  ) then
    return 'profanity';
  end if;

  if kind <> 'bio' and exists (
    select 1 from public.content_blocklist b
    where b.term <> '' and (
      (b.mode = 'res_exact' and sq = b.term)
      or (b.mode = 'res_contains' and position(b.term in sq) > 0)
      or (b.mode = 'res_prefix' and left(sq, length(b.term)) = b.term))
  ) then
    return 'impersonation';
  end if;

  if t ~* '(https?://|www\.|[a-z0-9-]+\.(com|net|org|io|gg|ly|me|co|app|xyz|ru|cn)\y|@[a-z0-9-]+\.[a-z]{2,})' then
    return 'link';
  end if;

  return null;
end;
$$;

revoke execute on function public.content_fold(text), public.content_words(text), public.content_flagged(text, text)
  from anon, public, authenticated;

create or replace function public.content_guard_message(issue text, kind text)
returns text
language sql
immutable
as $$
  select case
    when issue = 'link' then 'Links aren''t allowed here'
    when issue = 'impersonation' then 'That name is reserved'
    when kind = 'bio' then 'That bio isn''t allowed'
    else 'That name isn''t allowed'
  end;
$$;

revoke execute on function public.content_guard_message(text, text) from anon, public, authenticated;

create or replace function public.leaderboard_content_guard()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare issue text;
begin
  if new.display_name is not null and (tg_op = 'INSERT' or new.display_name is distinct from old.display_name) then
    issue := null;
    begin issue := public.content_flagged(new.display_name, 'name');
    exception when others then issue := null; end;
    if issue is not null and issue <> 'empty' then
      raise exception '%', public.content_guard_message(issue, 'name') using errcode = 'P0001';
    end if;
  end if;
  if new.bio is not null and (tg_op = 'INSERT' or new.bio is distinct from old.bio) then
    issue := null;
    begin issue := public.content_flagged(new.bio, 'bio');
    exception when others then issue := null; end;
    if issue is not null then
      raise exception '%', public.content_guard_message(issue, 'bio') using errcode = 'P0001';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists leaderboard_content_guard on public.leaderboard_entries;
create trigger leaderboard_content_guard
  before insert or update of display_name, bio on public.leaderboard_entries
  for each row execute function public.leaderboard_content_guard();

create or replace function public.title_content_guard()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare issue text;
begin
  if tg_op = 'INSERT' or new.name is distinct from old.name then
    issue := null;
    begin issue := public.content_flagged(new.name, 'title');
    exception when others then issue := null; end;
    if issue is not null and issue <> 'empty' then
      raise exception '%', public.content_guard_message(issue, 'name') using errcode = 'P0001';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists clubs_content_guard on public.clubs;
create trigger clubs_content_guard
  before insert or update of name on public.clubs
  for each row execute function public.title_content_guard();

drop trigger if exists tournaments_content_guard on public.tournaments;
create trigger tournaments_content_guard
  before insert or update of name on public.tournaments
  for each row execute function public.title_content_guard();

do $$ begin
  insert into public.schema_migrations (version) values ('0060_blocks_reports_content_filter')
    on conflict (version) do nothing;
exception when undefined_table then null;
end $$;
